// app/constants/subscriptionIcons.ts

// ----------------------------
// ÍCONES LOCAIS
// ----------------------------
export const SUBSCRIPTION_ICONS = {
  "99-taxi": require("@/assets/icons/subscriptions/99-taxi.png"),
  "adobe-creative-cloud": require("@/assets/icons/subscriptions/adobe-creative-cloud.png"),
  airtable: require("@/assets/icons/subscriptions/airtable.png"),
  "amazon-music": require("@/assets/icons/subscriptions/amazon-music.png"),
  "amazon-web-services-aws": require("@/assets/icons/subscriptions/amazon-web-services-aws.png"),
  "apple-arcade": require("@/assets/icons/subscriptions/apple-arcade.png"),
  "apple-music": require("@/assets/icons/subscriptions/apple-music.png"),
  "apple-one": require("@/assets/icons/subscriptions/apple-one.png"),
  "apple-tv-plus": require("@/assets/icons/subscriptions/apple-tv-plus.png"),
  asana: require("@/assets/icons/subscriptions/asana.png"),
  audible: require("@/assets/icons/subscriptions/audible.png"),
  audiomack: require("@/assets/icons/subscriptions/audiomack.png"),
  backblaze: require("@/assets/icons/subscriptions/backblaze.png"),
  behance: require("@/assets/icons/subscriptions/behance.png"),
  bitbucket: require("@/assets/icons/subscriptions/bitbucket.png"),
  canva: require("@/assets/icons/subscriptions/canva.png"),
  chatgpt: require("@/assets/icons/subscriptions/chatgpt.png"),
  clickup: require("@/assets/icons/subscriptions/clickup-symbol.png"),
  coursera: require("@/assets/icons/subscriptions/coursera.png"),
  crunchyroll: require("@/assets/icons/subscriptions/crunchyroll.png"),
  "curiosity-stream": require("@/assets/icons/subscriptions/curiosity-stream.png"),
  "deezer-2023": require("@/assets/icons/subscriptions/deezer-2023.png"),
  "disney-plus": require("@/assets/icons/subscriptions/Disney Plus.png"),
  dribbble: require("@/assets/icons/subscriptions/dribbble.png"),
  dropbox: require("@/assets/icons/subscriptions/dropbox.png"),
  duolingo: require("@/assets/icons/subscriptions/duolingo.png"),
  "ea-play": require("@/assets/icons/subscriptions/ea-play.png"),
  "epic-games": require("@/assets/icons/subscriptions/epic-games.png"),
  evernote: require("@/assets/icons/subscriptions/evernote.png"),
  figma: require("@/assets/icons/subscriptions/figma.png"),
  freepik: require("@/assets/icons/subscriptions/freepik.png"),
  funimation: require("@/assets/icons/subscriptions/funimation.png"),
  github: require("@/assets/icons/subscriptions/github.png"),
  gitlab: require("@/assets/icons/subscriptions/gitlab.png"),
  globoplay: require("@/assets/icons/subscriptions/globoplay.png"),
  "google-one": require("@/assets/icons/subscriptions/google-one.png"),
  "google-play-pass": require("@/assets/icons/subscriptions/google-play-pass.png"),
  "google-workspace": require("@/assets/icons/subscriptions/google-workspace.png"),
  "hbo-max": require("@/assets/icons/subscriptions/Hbo Max.png"),
  heroku: require("@/assets/icons/subscriptions/heroku.png"),
  idrive: require("@/assets/icons/subscriptions/idrive.png"),
  ifood: require("@/assets/icons/subscriptions/ifood.png"),
  kindle: require("@/assets/icons/subscriptions/kindle.png"),
  lionsgate: require("@/assets/icons/subscriptions/lionsgate.png"),
  looke: require("@/assets/icons/subscriptions/looke.png"),
  mega: require("@/assets/icons/subscriptions/mega-icon.png"),
  medium: require("@/assets/icons/subscriptions/medium.png"),
  "microsoft-365": require("@/assets/icons/subscriptions/microsoft-365.png"),
  midjourney: require("@/assets/icons/subscriptions/midjourney.png"),
  monday: require("@/assets/icons/subscriptions/monday.png"),
  mubi: require("@/assets/icons/subscriptions/mubi.png"),
  napster: require("@/assets/icons/subscriptions/napster.png"),
  netflix: require("@/assets/icons/subscriptions/netflix.png"),
  netlify: require("@/assets/icons/subscriptions/netlify.png"),
  "nintendo-switch": require("@/assets/icons/subscriptions/nintendo-switch.png"),
  nordvpn: require("@/assets/icons/subscriptions/nordvpn.png"),
  notion: require("@/assets/icons/subscriptions/notion.png"),
  onedrive: require("@/assets/icons/subscriptions/onedrive.png"),
  "pandora-jewelry": require("@/assets/icons/subscriptions/pandora-jewelry.png"),
  paramount: require("@/assets/icons/subscriptions/paramount.png"),
  placeholder: require("@/assets/icons/subscriptions/placeholder.png"),
  "pluto-tv": require("@/assets/icons/subscriptions/pluto-tv.png"),
  "prime-video": require("@/assets/icons/subscriptions/Amazon Prime Video.png"),
  "ps-plus": require("@/assets/icons/subscriptions/playstation-plus.png"),
  "rakuten-tv": require("@/assets/icons/subscriptions/rakuten-tv.png"),
  "slack-technologies": require("@/assets/icons/subscriptions/slack-technologies.png"),
  soundcloud: require("@/assets/icons/subscriptions/soundcloud.png"),
  spotify: require("@/assets/icons/subscriptions/spotify.png"),
  "star-plus": require("@/assets/icons/subscriptions/star-plus.png"),
  steam: require("@/assets/icons/subscriptions/steam.png"),
  strava: require("@/assets/icons/subscriptions/strava.png"),
  "sync-com": require("@/assets/icons/subscriptions/sync-com.png"),
  telecine: require("@/assets/icons/subscriptions/telecine.png"),
  tidal: require("@/assets/icons/subscriptions/tidal.png"),
  todoist: require("@/assets/icons/subscriptions/todoist.png"),
  trello: require("@/assets/icons/subscriptions/trello.png"),
  tresorit: require("@/assets/icons/subscriptions/tresorit.png"),
  twitch: require("@/assets/icons/subscriptions/twitch.png"),
  uber: require("@/assets/icons/subscriptions/uber.png"),
  ubisoft: require("@/assets/icons/subscriptions/ubisoft.png"),
  udemy: require("@/assets/icons/subscriptions/udemy.png"),
  vercel: require("@/assets/icons/subscriptions/vercel.png"),
  vimeo: require("@/assets/icons/subscriptions/vimeo.png"),
  wellhub: require("@/assets/icons/subscriptions/wellhub.png"),
  "whatsapp-business": require("@/assets/icons/subscriptions/whatsapp-business.png"),
  "xbox-game-pass": require("@/assets/icons/subscriptions/xbox-game-pass.png"),
  "youtube-music": require("@/assets/icons/subscriptions/youtube-music.png"),
  "youtube-premium": require("@/assets/icons/subscriptions/youtube-premium.png"),
} as const;

export type SubscriptionIconKey = keyof typeof SUBSCRIPTION_ICONS;

// ----------------------------
// ALIAS DE NOMES COMUNS
// ----------------------------
const SUBSCRIPTION_ICON_ALIASES: Record<string, SubscriptionIconKey> = {
  netflix: "netflix",
  "amazon prime video": "prime-video",
  "disney+": "disney-plus",
  "hbo max": "hbo-max",
  "paramount+": "paramount",
  globoplay: "globoplay",
  crunchyroll: "crunchyroll",
  lionsgate: "lionsgate",
  telecine: "telecine",
  mubi: "mubi",
  spotify: "spotify",
  "apple music": "apple-music",
  "amazon music": "amazon-music",
  tidal: "tidal",
  soundcloud: "soundcloud",
  "youtube premium": "youtube-premium",
  "youtube music": "youtube-music",
  deezer: "deezer-2023",
  notion: "notion",
  todoist: "todoist",
  trello: "trello",
  asana: "asana",
  clickup: "clickup",
  monday: "monday",
  aws: "amazon-web-services-aws",
  vercel: "vercel",
  netlify: "netlify",
  heroku: "heroku",
  backblaze: "backblaze",
  psplus: "ps-plus",
  xbox: "xbox-game-pass",
};

// ----------------------------
// FUNÇÃO DE ACESSO SEGURO
// ----------------------------
export function getSubscriptionIcon(serviceName: string): any {
  if (!serviceName) return SUBSCRIPTION_ICONS["placeholder"];

  const normalized = serviceName.toLowerCase().trim();
  const key = SUBSCRIPTION_ICON_ALIASES[normalized] || normalized;

  return SUBSCRIPTION_ICONS[key as SubscriptionIconKey] || SUBSCRIPTION_ICONS["placeholder"];
}
